### ISSUE TITLE
Cannot bundle ice-adapter

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/ice-adapter#12]
Currently @muellni have problems to bundle the app in one js file

https://faforever.slack.com/archives/ice-development/p1485248680000309

We tried 
* webpack https://github.com/IDragonfire/ice-adapter/tree/feature/bundle
with different modules
* node-external https://github.com/IDragonfire/ice-adapter/tree/feature/node-externals

App runs with

1. `npm install`
2. `npm run tscompile`
3. `node index.js --id 123 --login Rhiza﻿⁠⁠⁠⁠`

**Comment by muellni** [comment]
Ideally we ship a package for Windows which contains
- node.exe
- wrtc.node
- faf-ice-adapter.js (bundles sources)

**Comment by IDragonfire** [comment]
Maybe I found a solution ...
https://github.com/IDragonfire/ice-adapter/commit/1207f15fbba784e63292156813b65e5f89d00139

![image](https://cloud.githubusercontent.com/assets/1217999/22291123/013cf150-e305-11e6-8035-524380b737c3.png)


Zip file is ~9MB big
[ice-dist.zip](https://github.com/FAForever/ice-adapter/files/729689/ice-dist.zip)

1. Install node
2. Extract zip
3. Run `node faf-ice-adapter.js --id 1 --login 2`

**Comment by IDragonfire** [comment]
Or even better we ship only the `js` file and `pacakge.json` and run
`npm install --production` ^^

**Comment by muellni** [comment]
fixed with 2ef54f08af22b8f3e579ebf1baf769a9327783db
