### ISSUE TITLE
ICE access AudioSource

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/ice-adapter#15]
It looks like the current JS Adapter is sending Audiosignals ....
Kaspersky Security warns me:

"Program grant permission to receive audio signals"

https://help.kaspersky.com/Kis/2017/en-EN/94303.htm

![image](https://cloud.githubusercontent.com/assets/1217999/22292274/baa6ba5e-e30a-11e6-83a3-bb9f0476e6ff.png)

![image](https://cloud.githubusercontent.com/assets/1217999/22292334/f47c0d92-e30a-11e6-8917-53a88c564d20.png)

**Comment by muellni** [comment]
This is a webrtc issue which is very likely outside of my scope to fix. I'll close this for now, knowing that this might become a showstopper.
