### ISSUE TITLE
Fix ICE State 

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/ice-adapter#16]
Currently the ICE State flow looks a little bit broken ...

# How to Reproduce
1. One Test Client host the came
2. Alice/Bob/Charlie joins the game

# 2 Player Scenario

![image](https://cloud.githubusercontent.com/assets/1217999/22292995/31706c22-e30e-11e6-863d-5910644a6c83.png)

# 3 Player Scenario
![image](https://cloud.githubusercontent.com/assets/1217999/22293043/6a22eac2-e30e-11e6-9a23-f7949137b25a.png)

# 4 Player Sceanario
![image](https://cloud.githubusercontent.com/assets/1217999/22293129/b0298008-e30e-11e6-817b-1228d6fa999c.png)

# Notes
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/iceConnectionState

**Comment by IDragonfire** [comment]
https://bugs.chromium.org/p/webrtc/issues/detail?id=1414#c17

**Comment by muellni** [comment]
I think the testclient works better now. I saw both ICE states "connnected" and "complete" both led to successful connections.
