### ISSUE TITLE
Fix TURN on Windows

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/ice-adapter#17]
*TURN is working on Linux*

TURN candidates are not generated on Windows. But offered TURN candidates can be used.

# How to Reproduce
1. Only enable TURN
![image](https://cloud.githubusercontent.com/assets/1217999/22293212/13a3b82e-e30f-11e6-8461-9a3345e76b6d.png)
2. Host a game
3. Join the game

![image](https://cloud.githubusercontent.com/assets/1217999/22293361/9111e04c-e30f-11e6-9da0-fb7657d1cbe9.png)

# Notes

https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/iceGatheringState
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/iceConnectionState

**Comment by muellni** [comment]
It seems to work with this dll: https://github.com/FAForever/ice-adapter/releases/download/v5.0.0/wrtc.node
