### ISSUE TITLE
Test/implement reconnect

### ISSUE THREAD

**Issue by muellni** [FAForever/ice-adapter#23]
Make the testclient reconnect to the server, make it buffer ICE packages without server connection and test switching from LAN to Wifi

**Comment by micheljung** [comment]
Why would we buffer ICE packages? (maybe I don't understand what those packages are). If those are just game packages, I see no need to buffer them. If those are ICE specific messages, I'm also not sure they need to be buffered (ICE would just send them again, wouldn't it?).

**Comment by muellni** [comment]
I'm currently trying to figure out how to do reconnect with webrtc. I'm not sure if the testclient has to buffer the signalling packages.

**Comment by muellni** [comment]
I'm now creating a whole new rtcpeerconnection because ice-reconnect is currently unsupported by the node-webrtc bindings. This works most of the time.
