### ISSUE TITLE
Test all game connection modes

### ISSUE THREAD

**Issue by muellni** [FAForever/ice-adapter#33]
Test if matchmaker/ladder still works

**Comment by muellni** [comment]
A first test clicking the matchmaking button did not connect me

**Comment by muellni** [comment]
Are there any more game modes? I tested
- [x] Coop
- [x] join game
- [x] host game
- [ ] matchmaking faction click see #41

**Comment by micheljung** [comment]
Maybe this is caused by the "lobby mode" or "autolobby" flag? not sure. IIRC the ICE adapter just passes `1`, but it might just be another value.

**Comment by muellni** [comment]
automatch/ladder is working now. The ice-adapter now has a `setLobbyInitMode("auto"/"normal")` API method which need to be called before game launch.
