### ISSUE TITLE
node.exe in taskmanager increasing memory usage after few games

### ISSUE THREAD

**Issue by Nojoke185** [FAForever/ice-adapter#38]
Observed after the setons game that node.exe was using around 75000 (ish) kb of Ram
Prior to start of open palms game it started to constantly climb by about 4k per sec
At next game start (open palms) it seemed to stabilise and hold around 79mb

[ice-adapter.txt](https://github.com/FAForever/ice-adapter/files/856631/ice-adapter.txt)

Following palms game it was using 84332k and stable
Earlier in the day node had been using around 30mb

May be ok, logging for review if required

**Comment by muellni** [comment]
85 MB is way too much but I think nodejs' and webrtcs internal memory management is out of my reach. 
I will reopen this if node is indeed eating up users memory.
