### ISSUE TITLE
ConnectivityDialog needs theming

### ISSUE THREAD

**Issue by muellni** [FAForever/ice-adapter#39]
The QTableWidget vertical and horizontal headers need to be styled. Using `QHeaderView::section {
background-color: green; }` in `client.css` didn't work.

**Comment by Wesmania** [comment]
A widget needs to have a parent set to use parent's theming. From what I can see you use loadUi to make the widget, and I guess it doesn't set any parents. I'd suggest making a separate class for the dialog (as UI) that uses loadUiType, moving all the UI stuff there, then creating and operating on this in place of loadUi (passing it client as parent).

**Comment by muellni** [comment]
setting the dialogs parent was the thing which I implemented today, so the ConnectivityDialog is now  themed. Only things missing is the vertical and horizontal headers of the QTableWidget I use

**Comment by muellni** [comment]
https://github.com/FAForever/client/blob/feature/ice-adapter/src/connectivity/ConnectivityDialog.py#L24

**Comment by muellni** [comment]
solved by https://github.com/FAForever/client/blob/feature/ice-adapter/src/connectivity/ConnectivityDialog.py#L28

**Comment by muellni** [comment]
The vertical header still needs theming

**Comment by muellni** [comment]
fixed now I hope

**Comment by muellni** [comment]
now the second table entry still has a wrong background color

**Comment by muellni** [comment]
should be fixed ... again: https://github.com/FAForever/client/blob/feature/ice-adapter/res/client/client.css#L237
