### ISSUE TITLE
Fix matchmaking

### ISSUE THREAD

**Issue by muellni** [FAForever/ice-adapter#41]
From #33: A first test clicking the matchmaking button did not connect me

**Comment by Wesmania** [comment]
We did a test with duke - we connected fine, but the lobby didn't autolaunch, instead we were put into a regular lobby. It seems whether to launch automatically was dictated by an 'init_mode' member of GameSession, which was used as the first parameter of a "CreateLobby" GPG message. The member is still there, but ICE doesn't use it.
