### ISSUE TITLE
handle Alt+F4 for graceful disconnect

### ISSUE THREAD

**Issue by muellni** [FAForever/ice-adapter#50]
Current situation is that Alt-F4-quitting the game is connection lost for the other players. Maybe ice-adapter could send a disconnect packet to the other peers upon closed game.

**Comment by b2ag** [comment]
This would also be an improvement for other players when someones game crashes. Maybe only after  crashed player closes the stack trace dialog, but definitely an overall improvement.

**Comment by muellni** [comment]
The ice-adapter could only detect a closed game by a TCP disconnect in the GPGNet-connection.

**Comment by muellni** [comment]
Neither `EjectPeer` nor `DisconnectFromPeer` prevent the peer from timing out. I guess there's no way to make the peer being disconnected without timing out.
