### ISSUE TITLE
Investigate server additional ConnectToPeer call

### ISSUE THREAD

**Issue by muellni** [FAForever/ice-adapter#55]
It looks like the server is doing an unnecessary call to ConnectToPeer here: https://github.com/muellni/server/blob/feature/233-271-237-ICE/server/gameconnection.py#L167

**Comment by Sheeo** [comment]
No, that's necessary--`joinGame` does not actually establish a peer connection, so you need to send this in succession after that.

Notice the connection to the host is indeed only established once: https://github.com/muellni/server/blob/feature/233-271-237-ICE/server/gameconnection.py#L136.
